# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - MegaFirma

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e314fa9196bb4723ad9da44fcb07820d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f4ee302d407d4cfabc2dc1d6eef62327 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e314fa9196bb4723ad9da44fcb07820d }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MegaFirma'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5e5fd8685ad242d99a215faaa8154133 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e314fa9196bb4723ad9da44fcb07820d }}/appsvc/wordpress-alpine-php:${{ github.sha }}'